name: smart_attendance
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # UI enhancement packages
  google_fonts: ^6.1.0
  animated_text_kit: ^4.2.2
  flutter_svg: ^2.0.10+1
  shimmer: ^3.0.0
  
  # Functional packages
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  provider: ^6.1.2
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4
  firebase_messaging: ^15.2.5  # Added for push notifications
  flutter_local_notifications: ^19.1.0  # Added for local notifications
  image_picker: ^1.0.4
  http: ^1.1.0
  dio: ^5.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # Uncomment and add assets directory if needed
  # assets:
  #   - assets/images/
  #   - assets/icons/